version: 0.2

env:
  variables:
    TF_VERSION: "0.11.7"
    AWS_DEFAULT_REGION: "ap-northeast-1"

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - echo $TERRAFORM_VERSION
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin
  build:
    commands:
      - terraform -v | tee terraform.log
artifacts:
  files:
    - plan.log
