version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "0.11.7"

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - echo $TERRAFORM_VERSION
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip && unzip terraform.zip
      - mv terraform /usr/local/bin
      - apt-get -qq update
      - apt-get -qq install python3 python3-pip
      - echo "Validating terraform installs" && terraform -v
  build:
    commands:
      - cd aws
      - terraform init -input=false -no-color
      - terraform plan -out=tfplan -input=false -no-color | tee plan.log
      - terraform apply -input=false -no-color tfplan | tee apply.log
  #post_build:
  #  commands:
  #    - terraform plan -destroy -out=tfplan -input=false -no-color
  #    - terraform destroy -force -no-color
artifacts:
  files:
    - aws/plan.log
    - aws/apply.log
